 
version: '3'
services:

  spotify-me-tweets:
    container_name: spotify-me-tweets
    depends_on:
      - kafka
    build: .
    environment:
     - KafkaBootstrapServers=kafka:29092
     - KafkaKeySerializer=org.apache.kafka.common.serialization.StringSerializer
     - KafkaValueSerializer=org.apache.kafka.common.serialization.ByteArraySerializer
     - kafkaTopic=requisitions
     - HostPath=jsonplaceholder.typicode.com
     - UsersPath=/users
     - PORT=8080
     - HOST=0.0.0.0
     - consumerKey=
     - consumerSecret=
     - accessTokenKey=
     - accessTokenSecret=
     - hashtags=spotifyPlaylist
    ports:
      - "8080:8080"

  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1